services:
  # Backend Service
  - type: web
    name: claims-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        value: ""
      - key: H2_CONSOLE_ENABLED
        value: "false"
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: srivanivadthya@gmail.com
      - key: MAIL_PASSWORD
        value: fuowdnyqcwfajcpj
      - key: MAIL_AUTH
        value: "true"
      - key: MAIL_STARTTLS
        value: "true"

  # Frontend Service
  - type: web
    name: claims-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: claims-backend
          property: host